#!/bin/sh
if [ -z "$1" ]; then
  echo "Usage: $0 <commit> <branch>"
  echo "  branch is optimal and defaults to current"
  exit 1
fi
what_ref=$1
if [ -z "$2" ]; then
  branch="$(git symbolic-ref HEAD | sed 's|refs/heads/||')"
else
  branch="$2"
fi

git reflog show $branch@{now} | while read ref rest; do
  if [ -z "$(git rev-list -1 $ref..$what_ref)" ]; then
    printf "[x] "
  else
    printf "[ ] "
  fi
  echo $ref $rest
done | less -R
